dist: bionic
language: cpp

branches:
  only:
    - master
    - development

compiler:
  - clang   # clang 7
  - clang-9
  - gcc     # gcc 7.4
  - gcc-9
  - gcc-10

jobs:
  include:
    - name: "Build with LLVM/Clang 7"
    - compiler: clang
      env: 
        - MATRIX_EVAL="CC=clang CXX=clang++"

    - name: "Build with LLVM/Clang 9"
    - compiler: clang-9
      addons:
        apt:
          packages:
            - clang-9
      env: 
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

    - name: "Build with GCC 7.4"
    - compiler: gcc
      env: 
        - MATRIX_EVAL="CC=gcc CXX=g++"

    - name: "Build with GCC 9"
      compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      env: 
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - name: "Build with GCC 10"
      compiler: gcc-10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      env: 
        - MATRIX_EVAL="CC=gcc-10 CXX=g++-10"

before_script: 
- cmake --version
- eval "${MATRIX_EVAL}"
- $CC --version
- $CXX --version

script:
- mkdir ./build
- cd ./build
- cmake ..
- cmake --build .
- ctest
- cd ..

